name: branchwater-bench
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - sourmash>=4.9.2,<5
    - sourmash_plugin_branchwater>=0.9.13,<1
    - snakemake-minimal>=9,<10
    - rust=1.75
    - maturin>=1,<2
    - pip
